# .scrutinizer.yml
tools:
  external_code_coverage: false
filter:
    excluded_paths:
        - app/Support/Migration/*
        - app/database/migrations/*
        - database/migrations/*
build:
  tests:
    override:
      - coverage:
          file: 'storage/logs/clover.xml'
          format: 'clover'
  environment:
    php:
      version: 7.0
