language: php
addons:
  code_climate:
    repo_token: 8552db229501e4740a2c8e1c9e6269e48bbbf2001592033ff4209b286eb8a12f

php:
  - 7.0
env:
    - DB_CONNECTION=mysql
    - DB_CONNECTION=pgsql
    - DB_CONNECTION=sqlite
before_script:
  - cp .env.travis .env
  - if [[ "$DB_CONNECTION" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS firefly_test;" -U postgres; fi
  - if [[ "$DB_CONNECTION" == "pgsql" ]]; then psql -c "create database firefly_test;" -U postgres; fi
  - if [[ "$DB_CONNECTION" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS firefly_test;" -uroot; fi
  - if [[ "$DB_CONNECTION" == "sqlite" ]]; then touch firefly_test; fi
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed --env=testing
#script:
#  - vendor/bin/phpunit --coverage-text
after_script:
  - vendor/bin/test-reporter
