language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database firefly_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --seed --env=testing

script:
  - vendor/bin/phpunit --coverage-text
